## Dominant Value Function

In [1]:
import numpy as np

In [2]:
def Dominant_Eigenvalue(x):
    # A function to calculate eigenvalues and eigenvectors using numpy.
    eigenvalues, eigenvectors = np.linalg.eig(x)
    dominant_eigenvalue = np.max(np.abs(eigenvalues))
    return dominant_eigenvalue

x = np.array([[4, 1], [2, 3]])
print("Dominant eigenvalue:", Dominant_Eigenvalue(x))

Dominant eigenvalue: 5.0


## 2x2 Matrix inversse implementation 

In [3]:
def Matrix_Operations(A):
    # A function to get the inverse of 2x2 matrix.
    matrix_det = np.linalg.det(A)

    c = []
    for i in range(len(A)):
        for j in range(len(A[i])):
            c.append(A[i][j])

    c[0], c[3] = c[3], c[0]
    c[1], c[2] = -c[1], -c[2]
    matrix_A = np.array(c).reshape(2, 2)

    print("Determinant of matrix is", matrix_det, '\n')
    print("Cofactors matrix:\n", matrix_A, '\n')

    inversed_matrix = (1 / matrix_det) * matrix_A
    print("Inversed matrix:\n", inversed_matrix, '\n')

    identity_matrix = inversed_matrix @ A
    print("Identity matrix:\n", identity_matrix, '\n')


A = np.array([[2, 3], [2, 4]])
Matrix_Operations(A)

Determinant of matrix is 2.0 

Cofactors matrix:
 [[ 4 -3]
 [-2  2]] 

Inversed matrix:
 [[ 2.  -1.5]
 [-1.   1. ]] 

Identity matrix:
 [[1. 0.]
 [0. 1.]] 



## 3x3 Matrix inverse using numpy

In [4]:
A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print("3x3 Matrix inverse\n" ,np.linalg.inv(A))

3x3 Matrix inverse
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
